name: backend
description: Your go-to library for essential programming and tech books.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  path: ^1.9.0
  sembast: ^3.7.1
  zod_validation: ^1.0.5

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
